language: ruby
rvm:
  - 2.0.0
gemfile:
  - Gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.beta-versions
      rvm: 2.1.1
before_install:
  - CHROMEDRIVER_VERSION=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
  - CHROMEDRIVER_URL="http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
  - FILE=`mktemp`; wget "$CHROMEDRIVER_URL" -qO $FILE && sudo unzip $FILE chromedriver -d /usr/local/bin; rm $FILE; sudo chmod 777 /usr/local/bin/chromedriver
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable --force-yes
  - sudo chmod 1777 /dev/shm
  - sudo apt-get install fluxbox -y --force-yes
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - mkdir -p ~/.fluxbox
  - 'echo "session.screen0.fullMaximization: true" >> ~/.fluxbox/init'
  - fluxbox > /dev/null 2>&1 &
script: "bundle exec rake travis"
